version: '3.4'

services:
  ep.seabattle.web:
    image: ${DOCKER_REGISTRY-}epseabattleweb
    build:
      context: ./EP.SeaBattle.Web
      dockerfile: Dockerfile
    ports:
     - 8888:80
     
  seabattlefront:
    image: ${DOCKER_REGISTRY-}seabattlefront
    build:
      context: ./seabattle-game-client
      dockerfile: Dockerfile
    ports:
     - 9999:80