version: '3.4'

services:
  security:
    image: security
    build:
      context: ../EP.Hangman.Security
      dockerfile: Dockerfile
    ports:
      - 8088:80
    networks:
      default:
        ipv4_address: 172.19.0.10

  backend:
    image: backend
    build:
      context: ../EP.Hangman.Web/
      dockerfile: Dockerfile
    ports:
      - 8086:80
    networks:
      default:
        ipv4_address: 172.19.0.20
    environment:
      - DEBUG=1
    tty: true
    stdin_open: true

  frontend:
    image: frontend
    build:
      context: ../hangman-client
      dockerfile: Dockerfile
    ports:
      - 8084:80
    networks:
      default:
        ipv4_address: 172.19.0.30
    links:
      - security
      - backend
